TOKENIZERS_PARALLELISM=false CUDA_VISIBLE_DEVICES="4,5,6,7" accelerate launch --config_file  ~/yule-tx/RL4VLM/VLM_PPO/scripts/config_zero2.yaml --main_process_port 29489 ~/yule-tx/RL4VLM/VLM_PPO/main.py \
    --env-name gym_cards/Blackjack-v0 \
    --init-lr 1e-5 \
    --end-lr 1e-9 \
    --lr_max_steps 25 \
    --eval-num-per-episode 1000 \
    --num-env-steps 15000 \
    --num-steps 512 \
    --grad-accum-steps 128 \
    --max-new-tokens 256 \
    --thought-prob-coef 0.5 \
    --use-gae \
    --seed 1 \
    --temperature 0.2 \
    --ppo-epoch 4 \
    --mini-batch-size 1 \
    --model-path ~/yule-tx/models/llava-v1.6-mistral-7b-bj-sft \
    --use-lora \
    --train-vision all \
    --wandb-project RL4VLM \
    --wandb-run BlackJack-1 \
    --use-wandb \
    --q4